import Head from 'next/head';

type PropsTypes = {
  posts: PostsType;
};

type PostsType = {
  array: string[];
};

export async function getStaticProps() {
  const res = await fetch('https://localhost:3000/api/posts');
  const posts: PostsType = await res.json();

  return {
    props: {
      posts,
    },
  };
}

export default function Test({ posts }: PropsTypes) {
  return (
    <>
      <Head>
        <title>Test</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ul>
        {posts.array.map((post, i: number) => (
          <li key={i}>{post}</li>
        ))}
      </ul>
    </>
  );
}
