server:
  port: 8080
  servlet:
    context-path: /

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/hl_db
      username: root
      password: 123456

mybatis-plus:
  type-aliases-package: com.example.entity
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: isDeleted
      # table-prefix: t_

jwt:
  token:
    token-expiration: 604800  # 有效期 7 天，单位秒
    token-sign-key: headline123456  # 当前程序签名密钥，可以自定义
