server.port=80

spring.jdbc.datasource.driverClassName=com.mysql.cj.jdbc.driver
spring.jdbc.datasource.url=jdbc:mysql://localhost:3306/dbforspring
spring.jdbc.datasource.username=root
spring.jdbc.datasource.password=123456
